language: generic

sudo: required
dist: trusty
env:  
  - CLI_VERSION=latest

services:
  - docker

addons:
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - zlib1g
    - curl

before_install:
   # Try something else 
   - export DOTNET_INSTALL_DIR="$PWD/.dotnetcli"
   - curl -sSL https://raw.githubusercontent.com/dotnet/cli/rel/1.0.0-preview2/scripts/obtain/dotnet-install.sh | bash /dev/stdin --version "$CLI_VERSION" --install-dir "$DOTNET_INSTALL_DIR"
   - export PATH="$DOTNET_INSTALL_DIR:$PATH"
   # Add docker images
   - pushd src/ 
   - docker pull microsoft/dotnet
   - dotnet restore
   - dotnet publish -c Release -o bin/publish
   - docker build rolfwessels/coredocker:latest -t rolfwessels/coredocker:v0.0.1 .
   - popd
   
script:
  - which dotnet
  - dotnet --info
  - dotnet restore
  - pushd src/CoreDocker.Api && dotnet restore  && dotnet build
  - popd
  - pushd test/CoreDocker.Core.Tests && dotnet test 
  - popd
  #- pushd test/CoreDocker.Sdk.Tests && dotnet test 
  #- popd
  - pushd test/CoreDocker.Utilities.Tests && dotnet test 
  - popd
  - pushd test/CoreDocker.Dal.Tests && dotnet test 
  - popd
