os: Visual Studio 2015
install:
##   # .NET Core SDK binaries
##   ## 1) from direct url  
##   - ps: $url = "https://go.microsoft.com/fwlink/?LinkID=798402" # v1.0.0-preview1 x64
##   ## 2) from url based on version, for example using an env var CLI_VERSION that can be a
##   ##    a specific version `1.0.0-preview2-003121` or `Latest` (for latest dev version)
- ps: $env:CLI_VERSION = "1.0.0-preview2-003121"
- ps: $url = "https://dotnetcli.blob.core.windows.net/dotnet/preview/Binaries/$($env:CLI_VERSION)/dotnet-dev-win-x64.$($env:CLI_VERSION.ToLower()).zip"
# Download .NET Core SDK and add to PATH
- ps: $env:DOTNET_INSTALL_DIR = "$pwd\.dotnetsdk"
- ps: mkdir $env:DOTNET_INSTALL_DIR -Force | Out-Null
- ps: $tempFile = [System.IO.Path]::GetTempFileName()
- ps: (New-Object System.Net.WebClient).DownloadFile($url, $tempFile)
- ps: Add-Type -AssemblyName System.IO.Compression.FileSystem; [System.IO.Compression.ZipFile]::ExtractToDirectory($tempFile, $env:DOTNET_INSTALL_DIR)
- ps: $env:Path = "$env:DOTNET_INSTALL_DIR;$env:Path"

build_script:
  # dotnet info
  - ps: dotnet --info
  - ps: dotnet restore
  - ps: cd src/CoreDocker.Api 
  - ps: dotnet restore
  - ps: dotnet build
  - ps: cd ..\..
  - ps: cd test\CoreDocker.Core.Tests
  - ps: dotnet test  
  - ps: cd ..\..
  - ps: cd test\CoreDocker.Utilities.Tests
  - ps: dotnet test 
  - ps: cd ..\..
  - ps: cd test\CoreDocker.Api.Tests
  - ps: dotnet test 
  - ps: cd ..\..
  - ps: cd test\CoreDocker.Dal.Tests
  - ps: dotnet test 
  - ps: cd ..\..
  # - ps: cd test\CoreDocker.Sdk.Tests
  # - ps: dotnet test 
  # - ps: cd ..\..


test: off 
version: 0.0.1.{build}
